"""empty message

Revision ID: 8d55584ff214
Revises: 58c95bdf89e5
Create Date: 2025-07-23 21:29:48.702706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d55584ff214'
down_revision = '58c95bdf89e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentor', sa.Column('specialties', sa.ARRAY(sa.String(length=255)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mentor', 'specialties')
    # ### end Alembic commands ###
